### ISSUE TITLE
Mashup problem 

### ISSUE THREAD

**Issue by leCLEMS** [balexbyrd/sense-Funnel#1]
Hi ! 

When you use the visualisation in a mashup it doesn't work you only see : 
Invalid visualization
The visualization was not found on the server: d3Funnel

Seems like this is not included in the page, while I can see the extension in the ressources. (in chrome)

If you have any idea how to solve this.

**Comment by balexbyrd** [comment]
Hello!

I've experienced what you're seeing. A work around is in your mashup qlik js file, add d3 as a path, an example is below. It should be located at the top of your script.

```
require.config( {
     
     baseUrl: (config.isSecure ? "https://" : "http://" ) + config.host + (config.port ? ":" + config.port : "" ) + config.prefix + "resources",

     paths: {d3: "//cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3"}
});
```

**Comment by DATRQ** [comment]
I had same problem and edit the new paths but i think this path was down. Pls check this. Thanks
