### ISSUE TITLE
The extension is does not work now

### ISSUE THREAD

**Issue by gordanalozo** [balexbyrd/sense-Funnel#3]
It seems since we upgraded to Qlik Sense 3.2 the extension is not compatible any more.

**Comment by balexbyrd** [comment]
Hi Gordanalozo, would you be able to give me some more details?

What browser are you using?
How are you using the extension (inside qlik or in a mashup)?
What is the error or bug you're receiving?
How urgent is the need?

Thanks in advance!

**Comment by gordanalozo** [comment]
Hi,
Thanks for emailing back.
Here are details:
1. I was using IE and Chrome
2. I am using it inside Qlik Sense 3.2
3. The bug is, the whole funnel is missing from the chart, it looks like it's moved all the way to the left and all you can see are values for different stages on the very left.
4. It would be great if this can be fixed by the end of next week. I have a demo coming up and this chart was already part of the dashboard I developed. We upgraded to Qlik Sense 3.2.3 a few days ago and that is when I noticed the issue.

Thank you!!

**Comment by balexbyrd** [comment]
Hi gordanalozo,

Please clone and try again to confirm so I can close this out. I have this working as expected in v3.2 SR4 in Chrome. The changes made will work with QS 3.2.3 and work cross browser. Thanks!

**Comment by gordanalozo** [comment]
Hi,

Thank you so much for fixing this great extension. It works great now in Qlik 3.2. It is ready for my presentation now :)))

I really appreciate your help!

Thank you!
Gordana

**Comment by balexbyrd** [comment]
Glad it worked and you're welcome! Good luck on your demo.
