### ISSUE TITLE
Incorrect require.js config

### ISSUE THREAD

**Issue by mindspank** [balexbyrd/sense-Funnel#7]
Hey,

The require.js config in the main js file declares a d3 property. However it should probably be
```
require.config({
   paths: {
     d3: "//cdnjs.cloudflare.com/ajax/libs/d3/4.9.0/d3.min"
   }
})
```
With a incorrect config it would try to import the previously bundled version of D3 that shipped with Qlik Sense. From June 2018 and onwards we do no longer bundle d3 hence the import will fail.

**Comment by balexbyrd** [comment]
Thanks! I went ahead and updated d3 with d3.v4.min
