### ISSUE TITLE
Error - Invalid visualization

### ISSUE THREAD

**Issue by Nic3Guy** [balexbyrd/sense-Funnel#8]
Hi, after importing the zip file to the qmc extension, 
when i try to add the visualization to the report i get:

> **Invalid visualization:** The visualization was not found on the server: d3Funnel

![image](https://user-images.githubusercontent.com/17640648/43781528-c31cfa2c-9a65-11e8-986f-321380a9d16b.png)

can any one assist?

**Comment by balexbyrd** [comment]
What version of Qlik Sense are you using? This has been tested on QS June 2018 with no current plans of backward compatibility.
